version: '3.8'

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: nginx
        depends_on:
            - php
            - mysql
        ports:
            - 80:80
            - 443:443
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        networks:
            - laravel

    mysql:
        image: mysql:5.7.32
        container_name: mysql
        ports:
            - 4306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "php", "artisan" ]
        networks:
            - laravel

    npm:
        image: node:13.7
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "npm" ]
        networks:
            - laravel

    phpunit:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: phpunit
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "php", "artisan", "test" ]
        networks:
            - laravel
